<?php

ata_mysql_query("set names 'utf8'", $connection);

function szetbontTulajdonsagok($tulajdonsagok) {
    $tulajdonsag_lista = array(
        //színek
        'fehér' => 'szin',
        'világos kék' => 'szin',
        'kék' => 'szin',
        'fekete' => 'szin',
        'blue' => 'szin',
        'green' => 'szin',
        'pink' => 'szin',
        'turquoise' => 'szin',
        'yellow' => 'szin:sárga',
        'black' => 'szin:fekete',
        'brown' => 'szin:barna',
        'white' => 'szin:fehér',
        'pink' => 'szin:rózsaszín',
        'orange' => 'szin:narancs',
        'átlátszó' => 'szin',
        'transparent' => 'szin:átlátszó',
        'aqua sky' => 'szin:égszínkék',
        'glacier' => 'szin',
        'melon pop' => 'szin',
        'neon rose' => 'szin:rózsa',
        'ocean' => 'szin:óceán',
        'black/silver' => 'szin:fekete/ezüst',
        'grey/black' => 'szin:szürke/fekete',
        'grey' => 'szin:szürke',
        'silver/black' => 'szin:ezüst/fekete',
        'white/classic' => 'szin:fehér/klasszikus',
        'sárga' => 'szin',
        'piros' => 'szin',
        'brigth red' => 'szin:világos piros',
        'red' => 'szin:piros',
        'lila' => 'szin',
        'black/green' => 'szin:fekete/zöld',
        'black/red' => 'szin:fekete/piros',
        //kiszerelés univerzális
        'univerzális' => 'kiszereles',
        //méretezés
        'Slim' => 'meret',
        //vízállóság
        'vízálló' => 'vizallosag',
        //Védelem
        'víz- por- és ütésálló' => 'vedelem',
        //Kivitel
        'csatos-fűzős' => 'kivitel',
        //Anyag
        'valódi bőrtok' => 'anyag',
        'bőrtok' => 'anyag',
        'szilikon' => 'anyag',
        //gyári vagy nem
        'gyári' => 'eredetiseg',
        //Fólia típusa, képernyővédő vagy hátlapvédő stb.
        'képernyővédő fólia' => 'folia_tipus',
        'hátlapvédő fólia' => 'folia_tipus',
        'gyémántüveg' => 'folia_tipus',
        //átlátszóság
        'Clear' => 'lathatosag',
        'Anti-Glare' => 'lathatosag',
        'Anti-Finger' => 'lathatosag',
        'Frosted' => 'lathatosag',
        'Privacy' => 'lathatosag',
        'PRIVACY' => 'lathatosag:Privacy',
        'AntiCrash Crystal' => 'lathatosag',
        'Ultra Clear' => 'lathatosag',
        'Newlook/Crystal' => 'lathatosag',
        'Crystal/Antireflex HD' => 'lathatosag',
        'Glossy/Matt' => 'lathatosag',
        'AntiCrash Crystal' => 'lathatosag',
        //darab/csomag
        '3 db/csomag' => 'csomagolas',
        '2 db/csomag' => 'csomagolas',
        '1 db/csomag' => 'csomagolas',
        '1+3 db/csomag' => 'csomagolas',
        '2+2+2 db/csomag' => 'csomagolas',
        //hátlapok
        'ütésálló' => 'vedelem',
        'védőtok' => 'folia_tipus',
        'kartok' => 'folia_tipus',
        //Nyitás
        'oldalra nyitható' => 'kivitel:oldalra nyíló',
        'oldalra nyíló' => 'kivitel:oldalra nyíló',
        'kártyatartóval' => 'kivitel:kártyatartós',
        'lenyitható' => 'kivitel:lenyitható',
        'képernyővédő fóliával' => 'tartozek:védőfóliával',
        //Telefon Típusok APPLE
        'Apple iPhone 5C' => 'compatible_device',
        'Apple iPhone 6/6S' => 'compatible_device',
        'Apple iPhone 6 Plus/6S Plus' => 'compatible_device',
        'Apple iPhone 6 Plus' => 'compatible_device',
        'Apple iPhone 6' => 'compatible_device',
        'Apple iPhone 5/5S' => 'compatible_device',
        'Apple iPhone 4/4S' => 'compatible_device',
        'Apple iPhone 5C' => 'compatible_device',
        'Apple iPad Mini/iPad Mini 2' => 'compatible_device',
        'Apple iPad Mini/iPad Mini 2/iPad Mini 3' => 'compatible_device',
        'Apple iPad Air 2' => 'compatible_device',
        //Telefon Típusok Samsung
        'Samsung SM-G925 Galaxy S6 Edge' => 'compatible_device:Samsung Galaxy S6 Edge',
        'Samsung SM-A500F Galaxy A5' => 'compatible_device:Samsung Galaxy A5',
        'Samsung SM-A300F Galaxy A3' => 'compatible_device:Samsung Galaxy A3',
        'Samsung G3815 Galaxy Express 2' => 'compatible_device:Samsung Galaxy Express 2',
        'Samsung SM-G900 Galaxy S5' => 'compatible_device:Samsung Galaxy S5',
        'Samsung i8260 Galaxy Core' => 'compatible_device:Samsung Galaxy Core i8260',
        'Samsung i9500 Galaxy S4' => 'compatible_device:Samsung Galaxy S4',
        'Samsung SM-N910 Galaxy Note 4' => 'compatible_device:Samsung Galaxy Note 4',
        'Samsung SM-G850 Galaxy Alpha' => 'compatible_device:Samsung Galaxy Alpha',
        'Samsung S7570 Galaxy Trend 2' => 'compatible_device:Samsung Galaxy Trend 2',
        'Samsung SM-N7505 Galaxy Note 3 Neo' => 'compatible_device:Samsung Galaxy Note 3 Neo',
        'Samsung SM-G920 Galaxy S6' => 'compatible_device:Samsung Galaxy S6',
        'Samsung i9190 Galaxy S4 Mini' => 'compatible_device:Samsung Galaxy S4 Mini',
        'Samsung i9300 Galaxy S III' => 'compatible_device:Samsung Galaxy S3',
        'Samsung N7100 Galaxy Note II' => 'compatible_device:Samsung Galaxy Note 2',
        'Samsung i9200 Galaxy Mega 6.3' => 'compatible_device:Samsung Galaxy Mega 6.3',
        'Samsung i8190 Galaxy S III mini' => 'compatible_device:Samsung Galaxy S3 Mini',
        'Samsung S7560 Galaxy Trend' => 'compatible_device:Samsung Galaxy Trend',
        'Samsung S7270 Galaxy Ace 3' => 'compatible_device:Samsung Galaxy Ace 3',
        'Samsung SM-J500 Galaxy J5' => 'compatible_device:Samsung Galaxy J5',
        'Samsung SM-J500F Galaxy J5' => 'compatible_device:Samsung Galaxy J5',
        'Samsung SM-G130 Galaxy Young 2' => 'compatible_device:Samsung Galaxy Young 2',
        'Samsung N5100 Galaxy Note 8.0' => 'compatible_device:Samsung Galaxy Note 8.0',
        'Samsung N9000 Galaxy Note 3' => 'compatible_device:Samsung Galaxy Note 3',
        'Samsung SM-A700F Galaxy A7' => 'compatible_device:Samsung Galaxy A7',
        'Samsung SM-G357FZ Galaxy Ace 4' => 'compatible_device:Samsung Galaxy Ace 4',
        'Samsung S7562 Galaxy S Duos' => 'compatible_device:Samsung Galaxy S Duos',
        'Samsung SM-N915 Galaxy Note Edge' => 'compatible_device:Samsung Galaxy Note Edge',
        'Samsung SM-G7105/7105 Galaxy Grand 2' => 'compatible_device:Samsung Galaxy Grand 2',
        'Samsung G3500 Galaxy Core Plus' => 'compatible_device:Samsung Galaxy Core Plus',
        'Samsung S7572 Galaxy Trend II Duos' => 'compatible_device:Samsung Galaxy Trend 2 Duos',
        'Samsung SM-G800 Galaxy S5 Mini' => 'compatible_device:Samsung Galaxy S5 Mini',
        'Samsung SM-G386F Galaxy Core LTE' => 'compatible_device:Samsung Galaxy Core LTE',
        'Samsung i8190 Galaxy S III Mini' => 'compatible_device:Samsung Galaxy S3 Mini',
        'Samsung i8730 Galaxy Express' => 'compatible_device:Samsung Galaxy Express',
        'Samsung S6310 Galaxy Young' => 'compatible_device:Samsung Galaxy Young',
        'Samsung S7390 Galaxy Fresh' => 'compatible_device:Samsung Galaxy Fresh',
        'Samsung SM-G750 Galaxy Mega 2' => 'compatible_device:Samsung Galaxy Mega 2',
        'Samsung SM-G110 Galaxy Pocket 2' => 'compatible_device:Samsung Galaxy Pocket 2',
        'Samsung SM-A300 Galaxy A3' => 'compatible_device:Samsung Galaxy A3',
        'Samsung SM-E700F Galaxy E7' => 'compatible_device:Samsung Galaxy E7',
        'Samsung SM-E500F Galaxy E5' => 'compatible_device:Samsung Galaxy E5',
        'Samsung SM-A500 Galaxy A5' => 'compatible_device:Samsung Galaxy A5',
        //Kiegészítő típus
        'hátlap' => 'kiegeszito_jellege:Hátlap',
        'tok' => 'kiegeszito_jellege:Tok',
        'képernyővédő fólia' => 'kiegeszito_jellege:Fóliap',
        'töltő- és adatbkábel' => 'kiegeszito_jellege:Töltő és adatkábel',
        'VGA adapter' => 'kiegeszito_jellege',
        'hálózati töltő adapter' => 'kiegeszito_jellege:Hálózati töltő',
        'sztereó headset mikrofonnal' => 'kiegeszito_jellege:Headset',
        'Gyári akkumulátor' => 'kiegeszito_jellege:Gyári akkumulátor',
        'telefontartó' => 'kiegeszito_jellege:Telefontartó',
        'kihangosító' => 'kiegeszito_jellege:Kihangosító'
//        'Huawei' => 'cat_brand',
//        'Nokia' => 'cat_brand',
//        'Samsung' => 'cat_brand',
//        'Sony Ericsson' => 'cat_brand',
//        'Sony' => 'cat_brand',
//        'Apple' => 'cat_brand',
//        'LG' => 'cat_brand',
//        'Acer' => 'cat_brand',
//        'Alcatel' => 'cat_brand',
//        'Apple' => 'cat_brand',
//        'ASUS' => 'cat_brand',
//        'BlackBerry' => 'cat_brand',
//        'HTC' => 'cat_brand',
//        'Huawei' => 'cat_brand',
//        'Lenovo' => 'cat_brand',
//        'LG' => 'cat_brand',
//        'Microsoft' => 'cat_brand',
//        'Motorola' => 'cat_brand',
//        'Telenor' => 'cat_brand',
//        'Vodafone' => 'cat_brand',
//        'Wayteq' => 'cat_brand',
//        'ZTE' => 'cat_brand',
//        'AKAI' => 'cat_brand',
//        'Apollo' => 'cat_brand',
//        'ARCHOS' => 'cat_brand',
//        'BeeX' => 'cat_brand',
//        'Blaupunkt' => 'cat_brand',
//        'Bluepanther' => 'cat_brand',
//        'Colorovo' => 'cat_brand',
//        'ConCorde' => 'cat_brand',
//        'DPS' => 'cat_brand',
//        'Fujitsu' => 'cat_brand',
//        'Funscreen' => 'cat_brand',
//        'GoClever' => 'cat_brand',
//        'HP' => 'cat_brand',
//        'Kindle' => 'cat_brand',
//        'KOOBE' => 'cat_brand',
//        'Maxell' => 'cat_brand',
//        'Microsoft' => 'cat_brand',
//        'Modecom' => 'cat_brand',
//        'MyAudio' => 'cat_brand',
//        'MyPhone' => 'cat_brand',
//        'Navon' => 'cat_brand',
//        'Overmax' => 'cat_brand',
//        'Pentagram' => 'cat_brand',
//        'Point of View' => 'cat_brand',
//        'Prestigio' => 'cat_brand',
//        'Toshiba' => 'cat_brand',
//        'Xiaomi' => 'cat_brand',
//        'SAMSUNG' => 'cat_brand',
//        'NOKIA' => 'cat_brand',
//        'SAGEM' => 'cat_brand',
//        'Sagem' => 'cat_brand'
    );

    $megtalaltak = array();
    foreach ($tulajdonsag_lista as $tulajdonsag => $oszlop) {
        if (strpos($tulajdonsagok, $tulajdonsag) !== false && !isset($megtalaltak[$oszlop])) {
            $oszlopchunk = explode(':', $oszlop);
            if (count($oszlopchunk) > 1) {
                $megtalaltak[$oszlopchunk[0]] = $oszlopchunk[1];
            } else {
                $megtalaltak[$oszlop] = $tulajdonsag;
            }
        }
    }

    return $megtalaltak;
}
